all: *.cpp
	g++ -std=c++17 -lpthread -pthread -O2 -I../../or-tools/install_make/include -I../../or-tools/install_make -I../../or-tools/build_make/dependencies/install/include/ -I../../or-tools/install_make/ortools/gen -L../../or-tools/install_make/lib -L../../or-tools/install_make/lib64 *.cpp traci_lib/*.cpp -o x64/Release/main -lortools
